name: Add Issue to Project Column
on:
  issues:
    types:
      - labeled

jobs:
  add_to_column:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add issue to project column
        uses: octokit/request-action@v2.x
        with:
          route: POST /projects/columns/{column_id}/cards
          route-columns: ${{ github.event.repository.owner.login }},${{ github.event.repository.name }},'Todo'
          media-type: '{"previews":["inertia"]}'
          card: '{"content_id":${{ github.event.issue.id }},"content_type":"Issue"}'
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
